#!/usr/bin/env bash

testKeyValue() {
  local store

  store=$(mktemp)

  kv_create "$store"

  kv_set "$store" key value
  kv_set "$store" foo bar
  kv_set "$store" key other_value
  kv_set "$store" bar baz

  assertEquals "other_value" "$(kv_get "$store" key)"
  assertEquals "bar" "$(kv_get "$store" foo)"
  assertEquals "baz" "$(kv_get "$store" bar)"

  # if the key isn't there it should return an empty string
  assertEquals "" "$(kv_get "$store" not_there)"

  # kv_keys returns each key on a new line
  assertEquals "$(printf "%s\n" bar foo key)" "$(kv_keys "$store")"

  # kv_list returns key=value on individual lines
  assertEquals "$(printf "%s\n" bar=baz foo=bar key=other_value)" "$(kv_list "$store")"

  # calling create on an existing store doesn't erase it
  kv_create "$store"
  assertEquals "$(printf "%s\n" bar=baz foo=bar key=other_value)" "$(kv_list "$store")"

  # now clear the store
  kv_clear "$store"

  assertEquals "" "$(kv_get "$store" key)"
  assertEquals "" "$(kv_keys "$store")"
  assertEquals "" "$(kv_list "$store")"
}

testKeyValueNoNewLine() {
  local store

  # use a fixture that does not have an empty line after the final entry
  store="$(pwd)/test/unit-fixtures/kvstore/no-new-line"

  assertEquals "$(printf "%s\n" a=b b=c)" "$(kv_list "$store")"
  assertEquals "$(printf "%s\n" a b)" "$(kv_keys "$store")" 
}

testKeyValueEmptyLine() {
  local store

  # use a fixture that has an extra empty line
  store="$(pwd)/test/unit-fixtures/kvstore/empty-line"

  assertEquals "$(printf "%s\n" a=b b=c)" "$(kv_list "$store")"
  assertEquals "$(printf "%s\n" a b)" "$(kv_keys "$store")" 
}

testKeyValueEscaping() {
  local store
  store=$(mktemp)

  kv_create "$store"

  kv_set "$store" "key" "value with a space"
  assertEquals "key=\"value with a space\"" "$(kv_list "$store")"
  assertEquals "value with a space" "$(kv_get "$store" "key")"
}

# if the file doesn't exist, everything should be a no-op
testKeyValueNoFile() {
  local store="/tmp/does-not-exist"

  kv_set "$store" key value

  assertEquals "" "$(kv_get "$store" key)"
  assertEquals "" "$(kv_keys "$store")"
  assertEquals "" "$(kv_list "$store")"

  # running these commands has not created this file
  assertTrue "[[ ! -e $store ]]"
}

testKeyValueMultiLineString() {
  local store value

  store=$(mktemp)

  kv_create "$store"

  # create a multi-line string
  read -r -d '' value << EOM
This is line 1.
This is line 2.
Line 3.
EOM

  kv_set "$store" key "$value"

  # the value will be flattened into one line
  assertEquals "$(kv_get "$store" key)" "This is line 1. This is line 2. Line 3."
}

testKeyValueStringWithQuotes() {
  local store value build script

  store=$(mktemp)

  kv_create "$store"

  value="echo \"foo\" bar"
  build="node -e \"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'vendor/assets/bower_components', 'junction') } catch (e) { }\""
  script="if test \"\$NODE_ENV\" = \"production\"; then webpack --config webpack/webpack.config.prod.js; fi"

  kv_set "$store" key "$value"
  kv_set "$store" build "$build"
  kv_set "$store" script "$script"

  assertEquals "$(kv_get "$store" key)" "$value"
  assertEquals "$(kv_get_escaped "$store" key)" "\"echo \\\"foo\\\" bar\""

  assertEquals "$(kv_get "$store" build)" "$build"
  assertEquals "$(kv_get_escaped "$store" build)" "\"node -e \\\"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'vendor/assets/bower_components', 'junction') } catch (e) { }\\\"\""

  assertEquals "$(kv_get "$store" script)" "$script"
  assertEquals "$(kv_get_escaped "$store" script)" "\"if test \\\"\$NODE_ENV\\\" = \\\"production\\\"; then webpack --config webpack/webpack.config.prod.js; fi\""
}

# Keys must match [a-zA-Z_][a-zA-Z0-9_]+
testKeyNameEnforcement() {
  local store value out

  store=$(mktemp)

  kv_create "$store"

  out=$(kv_set "$store" "@foo" "value" 2>&1)
  # assert that the exit code was 0
  assertEquals "1" "$?"
  # assert the error message
  assertEquals "invalid param to kv_set '@foo'" "$out"

  out=$(kv_set "$store" "123" "value" 2>&1)
  # assert that the exit code was 0
  assertEquals "1" "$?"
  # assert the error message
  assertEquals "invalid param to kv_set '123'" "$out"
}

testKeyValueErrors() {
  local store value out

  store=$(mktemp)

  kv_create "$store"

  # an empty value string shouldn't fail
  out=$(kv_set "$store" "key" "" 2>&1)
  assertEquals "0" "$?"

  out=$(kv_set "$store" "key-with-no-value" 2>&1)
  assertEquals "1" "$?"
  assertEquals "Expected 3 arguments to kv_set, received 2" "$out"

  out=$(kv_set "$store" 2>&1)
  assertEquals "1" "$?"
  assertEquals "Expected 3 arguments to kv_set, received 1" "$out"

  out=$(kv_get "$store" 2>&1)
  assertEquals "1" "$?"
  assertEquals "Expected 2 arguments to kv_get, received 1" "$out"
}

testMetaData() {
  local cache_dir

  # prevent state from previous tests from polluting this one
  meta_force_clear

  cache_dir=$(mktemp -d)

  meta_init "$cache_dir" "buildpack-name"
  meta_setup

  meta_set "test" "foo"
  assertEquals "test=foo" "$(log_meta_data)"

  meta_set "test" "different-foo"
  assertEquals "test=different-foo" "$(log_meta_data)"

  meta_set "foo" "value with spaces"
  assertEquals "foo=\"value with spaces\" test=different-foo" "$(log_meta_data)"

  # values are printed with the keys sorted alphabetically
  # this isn't required, and this test serves as documentation
  meta_set "a" "this should come first"
  assertEquals "a=\"this should come first\" foo=\"value with spaces\" test=different-foo" "$(log_meta_data)"

  # dates generated by running `nowms; sleep 10; nowms`
  meta_time "time" "1545178120033" "1545178130043"
  assertEquals "10.010" "$(meta_get time)"

  # dates generated by running `nowms; sleep 1; nowms`
  meta_time "time" "1545178503025" "1545178504027"
  assertEquals "1.002" "$(meta_get time)"

  # dates generated by running `nowms; sleep 30; nowms`
  meta_time "time" "1545178521204" "1545178551206"
  assertEquals "30.002" "$(meta_get time)"
}

setupMetadata() {
  local cache_dir="$1"
  # create the data store
  meta_init "$cache_dir" "buildpack-name"
  meta_setup
  # store some data
  meta_set "foo" "bar"
}

testBuildDataInitIdempotent() {
  local cache_dir temp

  cache_dir="$(mktemp -d)"

  # prevent state from previous tests from polluting this one
  meta_force_clear

  # Set up the cache directory. This is run in a subshell so that the generated state
  # doesn't pollute this test. We only want the state on the disk.
  # shellcheck disable=SC2034
  temp=$(setupMetadata "$cache_dir")

  # To test this, let's make sure that get-ing "foo" returns nothing
  assertEquals "" "$(meta_get "foo")"

  # init the data store
  meta_init "$cache_dir" "buildpack-name"

  # The datastore created in the subshell should now work
  assertEquals "bar" "$(meta_get "foo")"

  # There should be no previous data
  assertEquals "" "$(meta_prev_get "foo")"
}

testBuildDataPreviousBuild() {
  local cache_dir

  cache_dir=$(mktemp -d)

  # the first time, there will be no previous build file
  meta_init "$cache_dir" "buildpack-name"
  meta_setup
  assertContains "buildpack-name" "$BUILD_DATA_FILE"
  assertContains "buildpack-name-prev" "$PREVIOUS_BUILD_DATA_FILE"
  assertFileExists "$BUILD_DATA_FILE"

  # set a value in the build data file
  meta_set "test" "foo"
  assertFileContains "test=foo" "$BUILD_DATA_FILE"
  assertFileDoesNotExist "$PREVIOUS_BUILD_DATA_FILE"

  assertEquals "$(meta_get test)" "foo"
  assertEquals "$(meta_prev_get test)" ""

  # the second time this is called (cache restored)
  # there will be a previous build file
  meta_init "$cache_dir" "buildpack-name"
  meta_setup
  assertFileExists "$BUILD_DATA_FILE"
  assertFileExists "$PREVIOUS_BUILD_DATA_FILE"

  # the data stored in the previous build should now be in the second file
  assertFileNotContains "test=foo" "$BUILD_DATA_FILE"
  assertFileContains "test=foo" "$PREVIOUS_BUILD_DATA_FILE"
  assertEquals "$(meta_get test)" ""
  assertEquals "$(meta_prev_get test)" "foo"
  meta_set "test" "bar"

  # doing it once more does not result in an error
  meta_init "$cache_dir" "buildpack-name"
  meta_setup
  assertFileExists "$BUILD_DATA_FILE"
  assertFileExists "$PREVIOUS_BUILD_DATA_FILE" 
  assertEquals "$(meta_prev_get test)" "bar"
  assertEquals "$(meta_get test)" ""
}

# the module to be tested
# shellcheck source=stdlib.sh
source "$(pwd)"/stdlib.sh

# shellcheck source=test/utils
source "$(pwd)"/test/utils
# import the testing framework
# shellcheck disable=SC1090
source "$(pwd)"/test/shunit2
